2024-01-13 01:01:10.375 [info] Extension host with pid 6134 started
2024-01-13 01:01:10.412 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2024-01-13 01:01:10.448 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2024-01-13 01:01:10.525 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2024-01-13 01:01:10.590 [info] Eager extensions activated
2024-01-13 01:01:10.599 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2024-01-13 01:01:10.601 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2024-01-13 01:01:10.619 [info] ExtensionService#_doActivateExtension ecmel.vscode-html-css, startup: false, activationEvent: 'onStartupFinished'
2024-01-13 01:01:20.463 [info] Extension host terminating: renderer closed the MessagePort
2024-01-13 01:01:20.469 [info] Extension host with pid 6134 exiting with code 0
2024-01-13 01:01:21.541 [info] Extension host with pid 6210 started
2024-01-13 01:01:21.541 [info] Skipping acquiring lock for /home/aexyzk/.config/Code - OSS/User/workspaceStorage/58e86b60f19fd9d010f9022fcac5e103.
2024-01-13 01:01:21.581 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2024-01-13 01:01:21.602 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2024-01-13 01:01:21.688 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2024-01-13 01:01:21.756 [info] Eager extensions activated
2024-01-13 01:01:21.777 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2024-01-13 01:01:21.779 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2024-01-13 01:01:21.795 [info] ExtensionService#_doActivateExtension ecmel.vscode-html-css, startup: false, activationEvent: 'onStartupFinished'
2024-01-13 01:01:25.748 [info] ExtensionService#_doActivateExtension ms-python.python, startup: false, activationEvent: 'onLanguage:python'
2024-01-13 01:01:26.027 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2024-01-13 01:01:27.274 [error] [ms-python.python] provider FAILED
2024-01-13 01:01:27.274 [error] Error: jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339625
	at re (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339919)
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334703
	at Immediate.<anonymous> (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334723)
	at process.processImmediate (node:internal/timers:476:21)
2024-01-13 01:01:27.275 [error] [ms-python.python] provider FAILED
2024-01-13 01:01:27.275 [error] Error: jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339625
	at re (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339919)
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334703
	at Immediate.<anonymous> (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334723)
	at process.processImmediate (node:internal/timers:476:21)
2024-01-13 01:01:27.322 [error] Error: Extension 'ms-python.python' CANNOT use API proposal: testObserver.
Its package.json#enabledApiProposals-property declares:  but NOT testObserver.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-python.python
	at v (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:138:48007)
	at get testResults [as testResults] (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:158:23805)
	at w.activate (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:795716)
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2455
	at Array.map (<anonymous>)
	at g.activateWorkspace (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2445)
2024-01-13 01:01:29.240 [info] ExtensionService#_doActivateExtension vscode.npm, startup: false, activationEvent: 'onTerminalQuickFixRequest:ms-vscode.npm-command'
2024-01-13 01:01:55.574 [error] [ms-python.python] provider FAILED
2024-01-13 01:01:55.574 [error] Error: jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339625
	at re (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339919)
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334703
	at Immediate.<anonymous> (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334723)
	at process.processImmediate (node:internal/timers:476:21)
2024-01-13 01:01:55.575 [error] [ms-python.python] provider FAILED
2024-01-13 01:01:55.575 [error] Error: jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339625
	at re (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339919)
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334703
	at Immediate.<anonymous> (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334723)
	at process.processImmediate (node:internal/timers:476:21)
2024-01-13 01:01:56.030 [error] [ms-python.python] provider FAILED
2024-01-13 01:01:56.030 [error] Error: jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339625
	at re (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339919)
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334703
	at Immediate.<anonymous> (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334723)
	at process.processImmediate (node:internal/timers:476:21)
2024-01-13 01:01:56.031 [error] [ms-python.python] provider FAILED
2024-01-13 01:01:56.032 [error] Error: jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339625
	at re (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339919)
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334703
	at Immediate.<anonymous> (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334723)
	at process.processImmediate (node:internal/timers:476:21)
2024-01-13 01:02:02.812 [error] [ms-python.python] provider FAILED
2024-01-13 01:02:02.812 [error] Error: jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339625
	at re (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339919)
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334703
	at Immediate.<anonymous> (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334723)
	at process.processImmediate (node:internal/timers:476:21)
2024-01-13 01:02:03.175 [error] [ms-python.python] provider FAILED
2024-01-13 01:02:03.175 [error] Error: jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339625
	at re (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339919)
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334703
	at Immediate.<anonymous> (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334723)
	at process.processImmediate (node:internal/timers:476:21)
2024-01-13 01:02:03.906 [error] [ms-python.python] provider FAILED
2024-01-13 01:02:03.906 [error] Error: jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339625
	at re (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339919)
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334703
	at Immediate.<anonymous> (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334723)
	at process.processImmediate (node:internal/timers:476:21)
2024-01-13 01:02:13.317 [error] [ms-python.python] provider FAILED
2024-01-13 01:02:13.317 [error] Error: jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339625
	at re (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339919)
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334703
	at Immediate.<anonymous> (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334723)
	at process.processImmediate (node:internal/timers:476:21)
2024-01-13 01:02:13.319 [error] [ms-python.python] provider FAILED
2024-01-13 01:02:13.319 [error] Error: jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339625
	at re (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339919)
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334703
	at Immediate.<anonymous> (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334723)
	at process.processImmediate (node:internal/timers:476:21)
2024-01-13 01:02:13.321 [error] [ms-python.python] provider FAILED
2024-01-13 01:02:13.321 [error] Error: jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339625
	at re (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339919)
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334703
	at Immediate.<anonymous> (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334723)
	at process.processImmediate (node:internal/timers:476:21)
2024-01-13 01:02:15.159 [error] [ms-python.python] provider FAILED
2024-01-13 01:02:15.159 [error] Error: jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339625
	at re (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339919)
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334703
	at Immediate.<anonymous> (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334723)
	at process.processImmediate (node:internal/timers:476:21)
2024-01-13 01:02:15.161 [error] [ms-python.python] provider FAILED
2024-01-13 01:02:15.161 [error] Error: jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339625
	at re (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339919)
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334703
	at Immediate.<anonymous> (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334723)
	at process.processImmediate (node:internal/timers:476:21)
2024-01-13 01:02:15.164 [error] [ms-python.python] provider FAILED
2024-01-13 01:02:15.164 [error] Error: jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339625
	at re (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339919)
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334703
	at Immediate.<anonymous> (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334723)
	at process.processImmediate (node:internal/timers:476:21)
2024-01-13 01:02:31.803 [error] [ms-python.python] provider FAILED
2024-01-13 01:02:31.803 [error] Error: jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339625
	at re (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339919)
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334703
	at Immediate.<anonymous> (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334723)
	at process.processImmediate (node:internal/timers:476:21)
2024-01-13 01:02:31.804 [error] [ms-python.python] provider FAILED
2024-01-13 01:02:31.804 [error] Error: jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339625
	at re (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339919)
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334703
	at Immediate.<anonymous> (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334723)
	at process.processImmediate (node:internal/timers:476:21)
2024-01-13 01:02:31.806 [error] [ms-python.python] provider FAILED
2024-01-13 01:02:31.806 [error] Error: jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339625
	at re (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339919)
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334703
	at Immediate.<anonymous> (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334723)
	at process.processImmediate (node:internal/timers:476:21)
2024-01-13 01:02:38.208 [error] [ms-python.python] provider FAILED
2024-01-13 01:02:38.208 [error] Error: jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339625
	at re (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339919)
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334703
	at Immediate.<anonymous> (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334723)
	at process.processImmediate (node:internal/timers:476:21)
2024-01-13 01:02:38.212 [error] [ms-python.python] provider FAILED
2024-01-13 01:02:38.212 [error] Error: jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339625
	at re (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339919)
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334703
	at Immediate.<anonymous> (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334723)
	at process.processImmediate (node:internal/timers:476:21)
2024-01-13 01:02:38.213 [error] [ms-python.python] provider FAILED
2024-01-13 01:02:38.214 [error] Error: jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339625
	at re (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339919)
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334703
	at Immediate.<anonymous> (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334723)
	at process.processImmediate (node:internal/timers:476:21)
2024-01-13 01:02:38.456 [error] [ms-python.python] provider FAILED
2024-01-13 01:02:38.456 [error] Error: jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339625
	at re (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2339919)
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334703
	at Immediate.<anonymous> (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2334723)
	at process.processImmediate (node:internal/timers:476:21)
2024-01-13 01:02:54.198 [info] Extension host terminating: renderer closed the MessagePort
2024-01-13 01:02:54.210 [info] Extension host with pid 6210 exiting with code 0
